name: cabal build

on:
  push:
    paths:
    - 'src/**'
    - 'Agda.cabal'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'
  pull_request:
    paths:
    - 'src/**'
    - 'Agda.cabal'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        ghc-ver: ["8.10.1"]
        cabal-ver: ["3.2"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: "~/.cabal"
        key: ${{ runner.os }}-cabal-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}
        restore-key: |
          ${{ runner.os }}-${{ matrix.ghc-ver }}-

    - name: Resolve dependencies
      run: |
        cabal update
        cabal configure -O0

#    - uses: actions/cache@v1
#      name: Cache dist-newstyle
#      with:
#        path: dist-newstyle
#        # The file `plan.json` contains the complete build information.
#        key: ${{ runner.os }}-dist-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ hashFiles('**/plan.json') }}
#
    - name: Install dependencies
      run: |
        cabal build --only-dependencies

    - name: Build Agda
      run: |
        cabal build
