name: Cabal build

on:
  push:
    paths:
    - 'src/**'
    - 'Agda.cabal'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'
    - 'Setup.hs'
    - 'test/**.hs'
  pull_request:
    paths:
    - 'src/**'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'
    - 'Agda.cabal'
    - 'Setup.hs'
    - 'test/**.hs'

jobs:
  auto-cancel:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')
    runs-on: Ubuntu-latest # Required, but it can be anything here.

    steps:
    - uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

  cabal:
    needs: auto-cancel

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        ghc-ver: [8.10.2]
        cabal-ver: [3.2]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Configure the build plan
      run: |
        cabal update
        cabal configure -O0

    - name: Add the path to icu4c to the cabal configuration
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "extra-lib-dirs: /usr/local/opt/icu4c/lib"         >> ~/.cabal/config
        echo "extra-include-dirs: /usr/local/opt/icu4c/include" >> ~/.cabal/config

    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: |
          ~/.cabal
        # The file `plan.json` contains the build information.
        key: ${{ runner.os }}-cabal-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ hashFiles('**/plan.json') }}

    - name: Install dependencies
      run: |
        cabal build --only-dependencies
    - name: Build Agda
      run: |
        cabal build

  cabal-on-win64:
    needs: auto-cancel
    name: "cabal"

    strategy:
      matrix:
        os: [windows-latest]
        ghc-ver: ["8.10.2.2"]
        cabal-ver: ["3.2"]

    runs-on: ${{ matrix.os }}
    env:
      # FLAGS: "-f enable-cluster-counting"
      FLAGS: ""
      ICU_FILE: "mingw-w64-x86_64-icu-65.1-1-any.pkg.tar.xz"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

          #    - name: Download and Install ICU ${{ matrix.icu-ver }}
          #      run: |
          #        C:\msys64\usr\bin\wget.exe -q http://repo.msys2.org/mingw/x86_64/${env:ICU_FILE}
          #        C:\msys64\usr\bin\pacman.exe -U --noconfirm ${env:ICU_FILE}
          #
          #        echo "extra-lib-dirs: C:\msys64\mingw64\lib"         >> cabal.config
          #        echo "extra-include-dirs: C:\msys64\mingw64\include" >> cabal.config
          #        type cabal.config
          #

    - name: Configure the build plan
      run: |
        cabal configure -O0

    - name: Build dependencies
      run: |
        cabal build ${FLAGS} --only-dependencies

    - name: Build Agda
      uses: nick-invision/retry@v2
      # Liang-Ting (2020-12-8):
      # Due to a ghc bug on Windows, it is necessary to build Agda twice (or more)
      # See:
      #   - https://github.com/agda/agda/issues/4543
      #   - https://gitlab.haskell.org/ghc/ghc/-/issues/18634
      with:
        max_attempts: 3
        timeout_minutes: 50
        retry_on: error
        command: cabal build ${{ env.FLAGS }}
