name: Whitespace
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.1'
          cabal-version: '3.2'
      - name: Install fix-agda-whitespace
        run: |
          cabal v1-update
          cd src/fix-agda-whitespace/
          cabal v1-install
          cd ../..
      - name: Check the whitespace issue
        run: |
          $HOME/.cabal/bin/fix-agda-whitespace --check
